server:
  port: 5555
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: siri
    password: siri
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
